import jsPDF from "jspdf";

// ─── Branding colours ────────────────────────────────────────────
const BRAND = {
    navy: [15, 23, 42] as const,       // header bg
    white: [255, 255, 255] as const,
    orange: [249, 115, 22] as const,    // accent
    grey: [100, 116, 139] as const,     // secondary text
    lightGrey: [241, 245, 249] as const,// table stripe
    green: [34, 197, 94] as const,
    yellow: [234, 179, 8] as const,
    red: [239, 68, 68] as const,
    black: [0, 0, 0] as const,
};

type RGB = readonly [number, number, number];

// ─── DutyDocsPDF wrapper ─────────────────────────────────────────
export class DutyDocsPDF {
    private doc: jsPDF;
    private y: number = 0;
    private pageWidth: number;
    private pageHeight: number;
    private margin = 20;
    private contentWidth: number;

    constructor() {
        this.doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
        this.pageWidth = this.doc.internal.pageSize.getWidth();
        this.pageHeight = this.doc.internal.pageSize.getHeight();
        this.contentWidth = this.pageWidth - this.margin * 2;
        this.y = this.margin;
    }

    // ── Header ──────────────────────────────────────────────────────
    addHeader(title: string, subtitle?: string) {
        // Navy banner
        this.doc.setFillColor(...BRAND.navy);
        this.doc.rect(0, 0, this.pageWidth, 32, "F");

        // Orange accent line
        this.doc.setFillColor(...BRAND.orange);
        this.doc.rect(0, 32, this.pageWidth, 1.5, "F");

        // Brand name
        this.doc.setFont("helvetica", "bold");
        this.doc.setFontSize(18);
        this.doc.setTextColor(...BRAND.white);
        this.doc.text("DutyDocs", this.margin, 14);

        // Subtitle tag
        this.doc.setFontSize(9);
        this.doc.setFont("helvetica", "normal");
        this.doc.setTextColor(180, 200, 220);
        this.doc.text("Health & Safety Management", this.margin, 20);

        // Document title
        this.doc.setFontSize(13);
        this.doc.setFont("helvetica", "bold");
        this.doc.setTextColor(...BRAND.white);
        this.doc.text(title, this.margin, 28);

        this.y = 40;

        if (subtitle) {
            this.doc.setFontSize(9);
            this.doc.setFont("helvetica", "normal");
            this.doc.setTextColor(...BRAND.grey);
            this.doc.text(subtitle, this.margin, this.y);
            this.y += 8;
        }
    }

    // ── Footer (called per-page) ────────────────────────────────────
    private addFooter(pageNum: number, totalPages: number) {
        const footerY = this.pageHeight - 10;
        this.doc.setFontSize(7);
        this.doc.setFont("helvetica", "normal");
        this.doc.setTextColor(...BRAND.grey);
        this.doc.text(
            `Generated by DutyDocs — ${new Date().toLocaleDateString("en-GB")}`,
            this.margin,
            footerY
        );
        this.doc.text(
            `Page ${pageNum} of ${totalPages}`,
            this.pageWidth - this.margin,
            footerY,
            { align: "right" }
        );
    }

    // ── Page break check ────────────────────────────────────────────
    private checkPageBreak(neededHeight: number) {
        if (this.y + neededHeight > this.pageHeight - 18) {
            this.doc.addPage();
            this.y = this.margin;
        }
    }

    // ── Section title ───────────────────────────────────────────────
    addSection(title: string) {
        this.checkPageBreak(14);
        this.y += 4;
        this.doc.setFontSize(11);
        this.doc.setFont("helvetica", "bold");
        this.doc.setTextColor(...BRAND.navy);
        this.doc.text(title.toUpperCase(), this.margin, this.y);
        this.y += 2;
        // underline
        this.doc.setDrawColor(...BRAND.orange);
        this.doc.setLineWidth(0.5);
        this.doc.line(this.margin, this.y, this.margin + this.contentWidth, this.y);
        this.y += 6;
    }

    // ── Key-value pair ──────────────────────────────────────────────
    addKeyValue(label: string, value: string | number | boolean | undefined) {
        if (value === undefined || value === "") return;
        this.checkPageBreak(8);
        const displayVal = typeof value === "boolean" ? (value ? "Yes" : "No") : String(value);

        this.doc.setFontSize(9);
        this.doc.setFont("helvetica", "bold");
        this.doc.setTextColor(...BRAND.navy);
        this.doc.text(`${label}:`, this.margin, this.y);

        this.doc.setFont("helvetica", "normal");
        this.doc.setTextColor(...BRAND.black);
        const labelWidth = this.doc.getTextWidth(`${label}: `) + 2;
        const maxWidth = this.contentWidth - labelWidth;
        const lines = this.doc.splitTextToSize(displayVal, maxWidth);
        this.doc.text(lines, this.margin + labelWidth, this.y);
        this.y += lines.length * 5 + 2;
    }

    // ── Multiline text block ────────────────────────────────────────
    addTextBlock(label: string, text: string | undefined) {
        if (!text) return;
        this.checkPageBreak(14);
        this.doc.setFontSize(9);
        this.doc.setFont("helvetica", "bold");
        this.doc.setTextColor(...BRAND.navy);
        this.doc.text(`${label}:`, this.margin, this.y);
        this.y += 5;

        this.doc.setFont("helvetica", "normal");
        this.doc.setTextColor(...BRAND.black);
        const lines = this.doc.splitTextToSize(text, this.contentWidth);
        for (const line of lines) {
            this.checkPageBreak(6);
            this.doc.text(line, this.margin, this.y);
            this.y += 5;
        }
        this.y += 2;
    }

    // ── Risk badge ──────────────────────────────────────────────────
    addRiskBadge(label: string, level: string, score?: number) {
        this.checkPageBreak(10);
        const color = this.riskColor(level);

        this.doc.setFontSize(9);
        this.doc.setFont("helvetica", "bold");
        this.doc.setTextColor(...BRAND.navy);
        this.doc.text(`${label}:`, this.margin, this.y);

        const labelW = this.doc.getTextWidth(`${label}: `) + 2;
        // Badge background
        const badgeText = score !== undefined ? `${level.toUpperCase()} (${score})` : level.toUpperCase();
        const badgeW = this.doc.getTextWidth(badgeText) + 6;
        this.doc.setFillColor(...color);
        this.doc.roundedRect(this.margin + labelW, this.y - 4, badgeW, 6, 1.5, 1.5, "F");
        this.doc.setTextColor(...BRAND.white);
        this.doc.setFontSize(8);
        this.doc.text(badgeText, this.margin + labelW + 3, this.y);
        this.y += 8;
    }

    // ── Status badge ────────────────────────────────────────────────
    addStatusBadge(label: string, status: string) {
        this.checkPageBreak(10);
        const color = this.statusColor(status);

        this.doc.setFontSize(9);
        this.doc.setFont("helvetica", "bold");
        this.doc.setTextColor(...BRAND.navy);
        this.doc.text(`${label}:`, this.margin, this.y);

        const labelW = this.doc.getTextWidth(`${label}: `) + 2;
        const badgeText = status.toUpperCase();
        const badgeW = this.doc.getTextWidth(badgeText) + 6;
        this.doc.setFillColor(...color);
        this.doc.roundedRect(this.margin + labelW, this.y - 4, badgeW, 6, 1.5, 1.5, "F");
        this.doc.setTextColor(...BRAND.white);
        this.doc.setFontSize(8);
        this.doc.text(badgeText, this.margin + labelW + 3, this.y);
        this.y += 8;
    }

    // ── Tags / list ─────────────────────────────────────────────────
    addTagList(label: string, items: string[] | undefined) {
        if (!items || items.length === 0) return;
        this.checkPageBreak(10);
        this.doc.setFontSize(9);
        this.doc.setFont("helvetica", "bold");
        this.doc.setTextColor(...BRAND.navy);
        this.doc.text(`${label}:`, this.margin, this.y);
        this.y += 5;

        this.doc.setFont("helvetica", "normal");
        this.doc.setTextColor(...BRAND.black);
        const joined = items.join("  •  ");
        const lines = this.doc.splitTextToSize(joined, this.contentWidth);
        for (const line of lines) {
            this.checkPageBreak(6);
            this.doc.text(line, this.margin, this.y);
            this.y += 5;
        }
        this.y += 2;
    }

    // ── Simple table ────────────────────────────────────────────────
    addTable(headers: string[], rows: string[][], colWidths?: number[]) {
        const cols = headers.length;
        const widths = colWidths || headers.map(() => this.contentWidth / cols);
        const rowH = 7;
        const headerH = 8;

        // Header row
        this.checkPageBreak(headerH + rowH);
        let x = this.margin;
        this.doc.setFillColor(...BRAND.navy);
        this.doc.rect(x, this.y - 5, this.contentWidth, headerH, "F");
        this.doc.setFontSize(8);
        this.doc.setFont("helvetica", "bold");
        this.doc.setTextColor(...BRAND.white);
        for (let i = 0; i < cols; i++) {
            this.doc.text(headers[i], x + 2, this.y);
            x += widths[i];
        }
        this.y += headerH - 2;

        // Data rows
        this.doc.setFont("helvetica", "normal");
        this.doc.setFontSize(8);
        for (let r = 0; r < rows.length; r++) {
            this.checkPageBreak(rowH + 2);
            x = this.margin;
            // Stripe
            if (r % 2 === 0) {
                this.doc.setFillColor(...BRAND.lightGrey);
                this.doc.rect(x, this.y - 4, this.contentWidth, rowH, "F");
            }
            this.doc.setTextColor(...BRAND.black);
            for (let c = 0; c < cols; c++) {
                const cellText = rows[r][c] || "";
                const truncated = this.doc.splitTextToSize(cellText, widths[c] - 4);
                this.doc.text(truncated[0] || "", x + 2, this.y);
                x += widths[c];
            }
            this.y += rowH;
        }
        this.y += 4;
    }

    // ── Checklist table (for inspections, DSE) ──────────────────────
    addChecklistTable(
        categoryName: string,
        items: { label: string; status: string; notes: string }[]
    ) {
        this.checkPageBreak(14);
        // Category header
        this.doc.setFontSize(9);
        this.doc.setFont("helvetica", "bold");
        this.doc.setTextColor(...BRAND.orange);
        this.doc.text(categoryName, this.margin, this.y);
        this.y += 5;

        const colWidths = [this.contentWidth * 0.55, this.contentWidth * 0.15, this.contentWidth * 0.30];
        this.addTable(
            ["Item", "Status", "Notes"],
            items.map((item) => [
                item.label,
                item.status === "pass" ? "✓ Pass" : item.status === "fail" ? "✗ Fail" : item.status === "na" ? "N/A" : "—",
                item.notes,
            ]),
            colWidths
        );
    }

    // ── Spacer ──────────────────────────────────────────────────────
    addSpacer(mm: number = 4) {
        this.y += mm;
    }

    // ── Save ────────────────────────────────────────────────────────
    save(filename: string) {
        // Add footers to all pages
        const totalPages = this.doc.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            this.doc.setPage(i);
            this.addFooter(i, totalPages);
        }
        this.doc.save(filename);
    }

    // ── Helpers ─────────────────────────────────────────────────────
    private riskColor(level: string): RGB {
        switch (level.toLowerCase()) {
            case "low": return BRAND.green;
            case "medium": return BRAND.yellow;
            case "high": return BRAND.orange;
            case "critical": return BRAND.red;
            default: return BRAND.grey;
        }
    }

    private statusColor(status: string): RGB {
        switch (status.toLowerCase()) {
            case "active": case "pass": case "valid": case "good":
            case "returned_to_work":
                return BRAND.green;
            case "pending": case "partial": case "expiring": case "fair":
            case "sent_home": case "draft":
                return BRAND.yellow;
            case "closed": case "expired": case "replace":
                return BRAND.grey;
            case "fail": case "major": case "serious": case "critical":
            case "hospital": case "ambulance":
                return BRAND.red;
            case "minor":
                return BRAND.green;
            case "moderate":
                return BRAND.orange;
            default:
                return BRAND.grey;
        }
    }
}

// ── Convenience: format date for PDF ─────────────────────────────
export function pdfDate(date: string | undefined): string {
    if (!date) return "—";
    try {
        return new Date(date).toLocaleDateString("en-GB", {
            day: "numeric",
            month: "short",
            year: "numeric",
        });
    } catch {
        return date;
    }
}

export function pdfDateTime(date: string | undefined): string {
    if (!date) return "—";
    try {
        return new Date(date).toLocaleDateString("en-GB", {
            day: "numeric",
            month: "short",
            year: "numeric",
            hour: "2-digit",
            minute: "2-digit",
        });
    } catch {
        return date;
    }
}
